<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_URL   - Search Console</name>
   <tag></tag>
   <elementGuidId>54b7d65d-d5e2-457d-9583-7f8980765ba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='goOtherCR(this,&quot;a=web_gen*w.link&amp;r=0&amp;i=a00000fa_8ce311ae1dc9a54743dc068c&amp;u=&quot;+urlencode(this.href))'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.link_tit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>50bd44ea-d5d8-4359-988e-9020ed4f0c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>34737247-c497-4a44-83e3-733d40507c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://support.google.com/webmasters/answer/9012289?hl=ko</value>
      <webElementGuid>d2aef663-857e-4960-9bbf-dc7cb4b35f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link_tit</value>
      <webElementGuid>aec70fc0-2a8e-44e8-a225-bd3da9dcd38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>goOtherCR(this,&quot;a=web_gen*w.link&amp;r=0&amp;i=a00000fa_8ce311ae1dc9a54743dc068c&amp;u=&quot;+urlencode(this.href))</value>
      <webElementGuid>2b9978a7-6dfd-48bd-8370-6550e2044e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>URL 검사 도구 - Search Console 고객센터</value>
      <webElementGuid>dc524939-d89d-4a40-b65e-faaccb440b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_pack&quot;)/section[@class=&quot;sc_new sp_ntotal _sp_ntotal _prs_web_gen _fe_root_web_gen&quot;]/div[@class=&quot;api_subject_bx type_noline&quot;]/ul[@class=&quot;lst_total&quot;]/li[@class=&quot;bx&quot;]/div[@class=&quot;total_wrap api_ani_send&quot;]/div[@class=&quot;total_group _tab_container&quot;]/div[@class=&quot;total_tit_box&quot;]/div[@class=&quot;total_tit&quot;]/a[@class=&quot;link_tit&quot;]</value>
      <webElementGuid>8ac24cb6-8562-45a8-9a52-aafa46d90a8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='goOtherCR(this,&quot;a=web_gen*w.link&amp;r=0&amp;i=a00000fa_8ce311ae1dc9a54743dc068c&amp;u=&quot;+urlencode(this.href))'])[3]</value>
      <webElementGuid>a2919a22-121f-4476-9d60-d8dbc1abb99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_pack']/section/div/ul/li/div/div[3]/div/div/a</value>
      <webElementGuid>8a16207e-09a6-45a0-a3d9-bb30a497cad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[2]/following::a[1]</value>
      <webElementGuid>bc7c11ef-5c1d-4785-808e-dabf2a052dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[1]/following::a[1]</value>
      <webElementGuid>40b17d7b-e959-4cb4-9ed3-a86668e8e674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='URL']/parent::*</value>
      <webElementGuid>5ddb549c-dc1d-465a-9948-896d4cdd3068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://support.google.com/webmasters/answer/9012289?hl=ko')])[3]</value>
      <webElementGuid>a7e9fb6e-922f-426e-b2c0-1565e45a8768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[3]/div/div/a</value>
      <webElementGuid>9d67ca06-c8bc-4507-8a23-11a640d6f70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://support.google.com/webmasters/answer/9012289?hl=ko' and (text() = 'URL 검사 도구 - Search Console 고객센터' or . = 'URL 검사 도구 - Search Console 고객센터')]</value>
      <webElementGuid>ad8fa9bc-2aea-4b5f-b2d3-212f76ba1cdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
