<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>87e178a5-2c8b-4a7b-8799-4f9b521913e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;NAVER&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3f5b034f-58d9-4429-86fb-6b4306e90c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ssl.pstatic.net/sstatic/search/nlogo/20230620232352.png</value>
      <webElementGuid>74ac7976-8566-4597-aa0f-dcfbb327837d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>58</value>
      <webElementGuid>15498b86-e9be-429a-9961-c557fb0c87f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>4a7f533d-8bf1-4329-b53e-6c1420b417cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>NAVER</value>
      <webElementGuid>549ed1ca-7f64-4355-a905-69f6a281fdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_wrap&quot;)/div[@class=&quot;api_floating_header&quot;]/div[@class=&quot;gnb_wrap&quot;]/div[@class=&quot;header_group&quot;]/div[@class=&quot;search_area&quot;]/h1[@class=&quot;logo special&quot;]/a[@class=&quot;link&quot;]/img[1]</value>
      <webElementGuid>83075e21-d161-4ca8-8f0c-1ff73f5d1580</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header_wrap']/div/div/div/div/h1/a/img</value>
      <webElementGuid>6d52bc3f-02f3-470d-a16f-bca59ca826e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='NAVER']</value>
      <webElementGuid>235f9f13-4af7-40e2-aa70-201000f010f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>dba5adfc-57d0-4a8e-aee7-b180d05b8922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ssl.pstatic.net/sstatic/search/nlogo/20230620232352.png' and @alt = 'NAVER']</value>
      <webElementGuid>920fe51d-5685-4300-9c4d-624a0c918b12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
