<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__search-btn</name>
   <tag></tag>
   <elementGuidId>9fb482d3-580a-4bc2-9717-e0a43b5c96c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='search-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>56d4c838-889a-42b3-999e-126885d5f516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-btn</value>
      <webElementGuid>b399dccb-9623-4120-87d0-c715e68c9ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico_btn_search type_color</value>
      <webElementGuid>2e530998-366d-43e1-a3d8-ebcbac8bad62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-btn&quot;)</value>
      <webElementGuid>75e111ed-fea3-42b0-ae1e-448257301dc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='search-btn']</value>
      <webElementGuid>0b118dce-add4-43b1-945c-ea2823f0e29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sform']/fieldset/button/span</value>
      <webElementGuid>86e3717c-a906-4528-80fc-60246feb608a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>7d1b3ed3-5878-4c99-aa4a-de902bb8e051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'search-btn']</value>
      <webElementGuid>7d4711dc-c860-49cb-b1db-534e5dc910b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
